SET SQL_MODE='ALLOW_INVALID_DATES';
CREATE TABLE `accounts` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`name` varchar(13) NOT NULL DEFAULT '',
	`password` varchar(128) NOT NULL DEFAULT '',
	`salt` varchar(32) DEFAULT NULL,
	`pin` varchar(134) DEFAULT NULL,
	`loggedin` tinyint(1) unsigned NOT NULL DEFAULT '0',
	`lastlogin` timestamp NULL DEFAULT NULL,
	`createdat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`birthday` date NOT NULL DEFAULT '1990-01-01',
	`banned` tinyint(1) NOT NULL DEFAULT '0',
	`banreason` text,
	`gm` tinyint(1) NOT NULL DEFAULT '0',
	`email` tinytext,
	`macs` tinytext,
	`tempban` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	`greason` tinyint(4) unsigned DEFAULT NULL,
	`maplepoints` int(11) NOT NULL DEFAULT '0',
	`gender` tinyint(1) unsigned NOT NULL DEFAULT '0',
	`SessionIP` varchar(64) DEFAULT NULL,
	`points` int(11) NOT NULL DEFAULT '0',
	`vpoints` int(11) NOT NULL DEFAULT '0',
	`dpoints` int(11) NOT NULL DEFAULT '0',
	`royalHair` bool NOT NULL DEFAULT 0,
	`nxCredit` varchar(45) NOT NULL DEFAULT '0',
	`monthvotes` int(11) NOT NULL DEFAULT '0',
	`totalvotes` int(11) NOT NULL DEFAULT '0',
	`lastvote` int(11) NOT NULL DEFAULT '0',
	`lastvote2` int(11) NOT NULL DEFAULT '0',
	`lastlogon` timestamp NULL DEFAULT NULL,
	`lastvoteip` varchar(64) DEFAULT NULL,
	`ip` text,
	`mainchar` int(6) NOT NULL DEFAULT '0',
	`sitelogged` text,
	`nick` varchar(20) DEFAULT NULL,
	`mute` int(1) DEFAULT '0',
    `verification_key` text DEFAULT NULL,
	
	PRIMARY KEY (`id`),
	UNIQUE KEY `name` (`name`),
	KEY `ranking1` (`id`,`banned`,`gm`),
	KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;